# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0

- script: |
    git remote add azure https://shakkozuuOrganization@dev.azure.com/shakkozuuOrganization/PurchaseBuddy/_git/PurchaseBuddy
    git config user.email shakkozuu@gmail.com
    git config user.name "Adam Kołodziejczyk"
    git push azure HEAD:refs/heads/main --force
  displayName: 'Push changes to Azure DevOps'
